public class MyClass {
    public MyClass() {
        
    }

    public static Integer sum(Integer a, Integer b) {
            return a + b;
    }

    public static Integer div(Integer a, Integer b) {
            return a / b;
    }

    public static Integer sub(Integer a, Integer b) {
            return a - b;
    }

    public static Integer mult(Integer a, Integer b) {
            return a * b;
    }
}